FROM python:3.13-alpine AS builder

RUN apk update
RUN apk add  build-base libffi-dev cargo pkgconfig

WORKDIR /src

RUN pip install poetry

COPY pyproject.toml ./
COPY README.md ./
COPY rns_page_node ./rns_page_node

RUN poetry build --format wheel

FROM scratch AS dist

COPY --from=builder /src/dist .
